from Bio import pairwise2
from Bio.pairwise2 import format_alignment
from Bio.Seq import Seq

# Séquences (à modifier selon ton cas)
orf25 = Seq("MTGCGVWWTTGLALLVIAVSPSLQQTTALNINSLVYSVSYSVPRFCGVNGLPYEISATFTFDKYNVSSVEWLAPVTPLPSTPGSRTNVTWALGRPHRTTLSFRPFVFTDATRPYAVRAMGEIIDVGLIKRYDDLPLGSVKAALLRVQAVGFDPVTSYAILKCVPSCSIRQDLRFVWFNYDQVQPGVSGDTLTTTVQGRYMCGVAGSQLFSKPIWVGEPVFDCPFDVRAWCPSGTVQKYENEYPRRYTEDDLRQPGTVLACNETKAVSTLGMCAERTVCNVEATNQCSDFSPAVYTSCNNTAVHKFCPDSLPFVWTSSTPWVVSTVDSNNIVFTDVPGTTSVINTFCGAETNVYLLCGTPEQAVSAARPRPVFSIPTLDTMTVANGDGVVPELSVVREGTVFEMECPSPNLVVYWRRGNLRMAVSLGSSNVRILRKTLTREDLNATWSCVGFDSYNAITATLFRSVYLTDVKPTTPAPATSTTTTPTLPVTTPKTTTLRTTTLPAPPTITTTTPGSSTGAGTSQGPSTALPTTFTTPTLTVAPDEGSSGALVVLIVITVFEALIIVFVIVVCGCYYYKHNPELRHAVEEFTKRKAKEDIKRFGAQVSRRP")  # Remplace par ta séquence complète ORF25
deleted_seq = Seq("TTFTTPTLTVAPDEGSSGALVVLIVITVFEALIIVFVIVVCGCYYYKHNPELRHAVEEFTRKAKEDIKRFGAQVSRRPNTIAGDGSGRRVIFLSGGSIILPWSTVSPVPRGCSPVTATASGARPWAWPSAWPCSPAWCRCPTPSTASRTICPVEGQNFTMRATFFTDNLTIINAFWFFSSTPNVRPSTTKFITTFSRVPGSPDQWQTVLTIVGFTAATDANRVFNFRRVLVPRRHVRQLAQHPRHRGQVGHQLHHRADGHHQRRAGITCPAESSTRWGTSACSIRTSLASLSKPSSPQTTSSGAASHTPHTPGSWATSGPGPRSSSPRSPPPLSQLPRRRPRRRHQPPPRQPQAPPPRRLQNHRKHPGSHRRKHYHHHNPRHPAADRGAQHPAHHHRRPLHHALRLGRGDRGRGRALRRSRQPGRLLLLTFQIKQCQRIIFLDLVDFLSVCTPVNRGHIMGIMPNSVWLAEPLPLLLYLLLLPSPIDAFYAVKYSSPTSATCPIAGQPYVVQALFQADNRTVTARDGTPPTASSPSPPSRPEPTSPSGKPVTLGPPGSPRPSSRRTPRRTCSCYSATRPTPSVSPSPPTSPCPQRPPSGTPASTWCDVYRPATDPAPTPGASTTPPSLEPSRRTSPSRHRATTPVLTPIPQSPTPPSSSSRRRPRRKRPTPQP")  # Remplace par ta séquence délétée

# Alignement global (Needleman-Wunsch)
alignments = pairwise2.align.globalxx(orf25, deleted_seq)

# Sélection du meilleur alignement
best_alignment = alignments[0]
aligned_orf25, aligned_deleted = best_alignment.seqA, best_alignment.seqB

# Identifier les résidus de l'ORF25 présents dans la séquence délétée
orf25_positions_to_remove = [i for i, (aa_orf25, aa_del) in enumerate(zip(aligned_orf25, aligned_deleted)) if aa_orf25 == aa_del and aa_del != "-"]

# Calcul de la proportion d'ORF25 conservée
conserved_count = len(orf25_positions_to_remove)
total_length_orf25 = len(orf25)
proportion_conserved = conserved_count / total_length_orf25 * 100

# Suppression des acides aminés conservés de l'ORF25
orf25_light = "".join(aa for i, aa in enumerate(orf25) if i not in orf25_positions_to_remove)

# Résultats
print(f"Proportion d'ORF25 conservée dans la séquence délétée : {proportion_conserved:.2f}%")
print(f"Nouvelle séquence ORF25 allégée :\n{orf25_light}")

# Sauvegarde de la séquence allégée
with open("orf25_light.fasta", "w") as f:
    f.write(f">ORF25_light\n{orf25_light}\n")

